def extend_point_on_line(point1, point2, distance):
  '''
  Args:
    point1: type array two values [x, y].
    point2: type array two values [x, y].
    distance: type float.
  Returns:
    A new point, point3, which is on the same
    line generated by point1 and point2.
  '''
  vector = substract(point2, point1)
  norm = distance / magnitude(vector)
  new_point_x = point2[0] + norm * vector[0]
  new_point_y = point2[1] + norm * vector[1]
  return [new_point_x, new_point_y]

